// Program Learning Library — mock dataset
window.PLL_DATA = (function () {
  const now = new Date('2026-04-13');
  const daysAgo = (d) => {
    const x = new Date(now); x.setDate(x.getDate() - d);
    return x.toISOString().slice(0, 10);
  };

  const docs = [
    {
      id: 'd01',
      title: "The Role of Women in Community-Driven Sanitation Transformation in Rwanda",
      authors: ["Louis Pascal Mabimpano"],
      type: "Blog",
      thumb: "blog",
      date: daysAgo(0),
      geography: ["Rwanda"],
      topics: ["Community Finance", "Sanitation", "Gender"],
      tags: ["community finance", "district WASH office", "blog", "Africa"],
      language: "EN",
      partners: ["District WASH Office"],
      funders: [],
      collection: "Learning & Innovation Agenda",
      summary: "This article describes how women have leveraged VSLA financial access and community leadership to push sanitation and hygiene to the forefront, while men have shown up through targeted engagement and peer motivation.",
      views: 342, downloads: 58, pages: 4,
    },
    {
      id: 'd02',
      title: "District WASH Budget Allocations in Rwanda",
      authors: ["Stephen Mugabo"],
      type: "Technical Note",
      thumb: "tech",
      date: daysAgo(0),
      geography: ["Rwanda"],
      topics: ["Government Systems", "Finance"],
      tags: ["district WASH office", "case study", "Africa"],
      language: "EN",
      partners: ["District WASH Office"],
      funders: ["Hilton Foundation"],
      collection: "Scaling with Government",
      summary: "This technical note examines per-capita WASH budget allocations across ten Rwandan districts from fiscal year 2021/22 through 2024/25, offering insights into investment trends, challenges, and implications for long-term sustainability.",
      views: 1204, downloads: 322, pages: 16,
    },
    {
      id: 'd03',
      title: "Sanitation Business Viability in Rwanda",
      authors: ["Aimable Mugabo", "Clare Battle"],
      type: "Case Study",
      thumb: "case",
      date: daysAgo(9),
      geography: ["Rwanda"],
      topics: ["Sanitation", "Enterprise"],
      tags: ["sanitation enterprise", "MSME", "case study", "Africa"],
      language: "EN",
      partners: [],
      funders: ["USAID"],
      collection: "Scaling with Government",
      summary: "A mixed-methods assessment of sanitation MSMEs operating in Rusizi and Gicumbi districts, examining profitability, supply-chain choke points, and what drove the most resilient entrepreneurs through the 2024 price shocks.",
      views: 887, downloads: 201, pages: 22,
    },
    {
      id: 'd04',
      title: "From Subsidy to System: Sustainable Rural Water Finance in Uganda",
      authors: ["Brenda Achieng", "Peter Musoke"],
      type: "Report",
      thumb: "tech",
      date: daysAgo(22),
      geography: ["Uganda"],
      topics: ["Finance", "Rural Water Supply", "Government Systems"],
      tags: ["life-cycle cost", "tariff", "rural water", "Africa"],
      language: "EN",
      partners: ["Ministry of Water and Environment"],
      funders: ["Conrad N. Hilton Foundation"],
      collection: "Scaling with Government",
      summary: "Examines how three Ugandan districts transitioned from subsidy-dependent infrastructure to financially sustainable service delivery — and the governance shifts that made it stick.",
      views: 2345, downloads: 611, pages: 48,
    },
    {
      id: 'd05',
      title: "Escuela Azul: Integrating WASH into Honduran Primary Schools",
      authors: ["Marcela Reyes"],
      type: "Case Study",
      thumb: "case",
      date: daysAgo(31),
      geography: ["Honduras"],
      topics: ["Schools", "Hygiene", "Government Systems"],
      tags: ["escuela azul", "schools", "hygiene", "Latin America"],
      language: "ES",
      partners: ["Secretaría de Educación"],
      funders: [],
      collection: "Learning & Innovation Agenda",
      summary: "La iniciativa Escuela Azul ha certificado 312 escuelas en cuatro departamentos. Este estudio documenta los factores institucionales y pedagógicos que permitieron sostener los comportamientos de higiene más allá del cierre del proyecto.",
      views: 1098, downloads: 287, pages: 28,
    },
    {
      id: 'd06',
      title: "Monitoring Framework for Circuit-Rider Maintenance Models",
      authors: ["Dev Patel", "Nancy Kawira"],
      type: "Tool",
      thumb: "deck",
      date: daysAgo(44),
      geography: ["Kenya", "Malawi", "Honduras"],
      topics: ["Service Delivery", "Monitoring", "Finance"],
      tags: ["circuit rider", "O&M", "monitoring", "tool"],
      language: "EN",
      partners: [],
      funders: ["Hilton Foundation"],
      collection: "Sustainable Services",
      summary: "A modular spreadsheet-based framework for tracking circuit-rider maintenance coverage, response times, and spare-parts availability across piped and point-source systems.",
      views: 512, downloads: 189, pages: 12,
    },
    {
      id: 'd07',
      title: "Lessons from the Everyone Forever Model: Ten Year Retrospective",
      authors: ["Dan Matteson", "Eleanor Allen"],
      type: "Report",
      thumb: "tech",
      date: daysAgo(61),
      geography: ["Global"],
      topics: ["Strategy", "Service Delivery"],
      tags: ["everyone forever", "strategy", "retrospective"],
      language: "EN",
      partners: [],
      funders: [],
      collection: "Strategy",
      summary: "A decade of implementing the Everyone Forever model across nine countries: what worked, what didn't, and what the next ten years demand of us.",
      views: 4201, downloads: 1103, pages: 64,
    },
    {
      id: 'd08',
      title: "Scaling with Government: Bihar State Partnership Deep Dive",
      authors: ["Priya Sharma", "Rajesh Kumar"],
      type: "Presentation",
      thumb: "deck",
      date: daysAgo(73),
      geography: ["India"],
      topics: ["Government Systems", "Scale"],
      tags: ["India", "government partnership", "scale", "Asia"],
      language: "EN",
      partners: ["Public Health Engineering Department, Bihar"],
      funders: [],
      collection: "Scaling with Government",
      summary: "Slide deck from the January 2026 board retreat outlining the Bihar state partnership, covering 42 districts and 12M people, and the MOU structure underpinning it.",
      views: 889, downloads: 145, pages: 32,
    },
    {
      id: 'd09',
      title: "Agua Segura en Zonas Periurbanas de Guatemala",
      authors: ["Juan Carlos Méndez"],
      type: "Case Study",
      thumb: "case",
      date: daysAgo(88),
      geography: ["Guatemala"],
      topics: ["Urban Water", "Service Delivery", "Community Finance"],
      tags: ["peri-urban", "water safety", "Latin America"],
      language: "ES",
      partners: [],
      funders: [],
      collection: "Sustainable Services",
      summary: "Un análisis de cuatro barrios periurbanos de la Ciudad de Guatemala donde los comités comunitarios de agua han logrado mantener servicios continuos a pesar de la presión migratoria y los cortes de energía.",
      views: 721, downloads: 143, pages: 18,
    },
    {
      id: 'd10',
      title: "WASH Systems Change Measurement: A Practitioner's Guide",
      authors: ["Ellen Greggio", "Arjun Das"],
      type: "Tool",
      thumb: "deck",
      date: daysAgo(104),
      geography: ["Global"],
      topics: ["Monitoring", "Systems Change", "Strategy"],
      tags: ["systems change", "measurement", "M&E"],
      language: "EN",
      partners: ["Agenda for Change"],
      funders: [],
      collection: "Learning & Innovation Agenda",
      summary: "A companion guide to the Systems Change Framework, with adaptable indicators, data collection templates, and three worked examples from Bolivia, Uganda, and India.",
      views: 1567, downloads: 544, pages: 56,
    },
    {
      id: 'd11',
      title: "Community Capacity Strengthening: Video Series Introduction",
      authors: ["Communications Team"],
      type: "Video",
      thumb: "video",
      date: daysAgo(120),
      geography: ["Bolivia", "Peru"],
      topics: ["Community Capacity", "Training"],
      tags: ["video", "training", "Latin America"],
      language: "ES",
      partners: [],
      funders: [],
      collection: "Training",
      summary: "Episodio 1 de una serie de 6 videos sobre fortalecimiento comunitario. Introducción al enfoque y los cuatro pilares del modelo.",
      views: 2103, downloads: 0, pages: 0,
    },
    {
      id: 'd12',
      title: "Results-Based Financing in the Water Sector: Early Signals",
      authors: ["Kevin O'Brien"],
      type: "Technical Note",
      thumb: "tech",
      date: daysAgo(135),
      geography: ["Rwanda", "Malawi"],
      topics: ["Finance", "Government Systems"],
      tags: ["RBF", "results-based financing", "innovation"],
      language: "EN",
      partners: ["World Bank"],
      funders: ["World Bank"],
      collection: "Innovation",
      summary: "Preliminary findings from two pilots of results-based financing for rural water operators. Early signals on verification cost, operator response, and perverse incentives to avoid.",
      views: 677, downloads: 198, pages: 14,
    },
    {
      id: 'd13',
      title: "Climate Resilience in Small-Town Water Systems",
      authors: ["Fatima Hussein", "Dan Matteson"],
      type: "Report",
      thumb: "tech",
      date: daysAgo(155),
      geography: ["Malawi", "Uganda"],
      topics: ["Climate", "Service Delivery", "Urban Water"],
      tags: ["climate", "resilience", "small towns"],
      language: "EN",
      partners: [],
      funders: ["Conrad N. Hilton Foundation"],
      collection: "Climate",
      summary: "Assesses vulnerability and adaptation options for 23 small-town water systems facing increasingly variable rainfall and prolonged dry seasons.",
      views: 934, downloads: 266, pages: 38,
    },
    {
      id: 'd14',
      title: "Menstrual Health & Hygiene in WASH Programming",
      authors: ["Sarah Okello"],
      type: "Blog",
      thumb: "blog",
      date: daysAgo(170),
      geography: ["Uganda"],
      topics: ["Hygiene", "Gender", "Schools"],
      tags: ["MHH", "gender", "schools", "Africa"],
      language: "EN",
      partners: [],
      funders: [],
      collection: "Learning & Innovation Agenda",
      summary: "Reflections from the field on integrating menstrual health and hygiene components into school WASH programming, and the quiet shifts in uptake when girls help design the facilities.",
      views: 445, downloads: 67, pages: 5,
    },
    {
      id: 'd15',
      title: "Tariff-Setting Methodologies: A Comparative Review",
      authors: ["Arjun Das"],
      type: "Technical Note",
      thumb: "tech",
      date: daysAgo(188),
      geography: ["Global"],
      topics: ["Finance", "Service Delivery"],
      tags: ["tariff", "finance", "review"],
      language: "EN",
      partners: [],
      funders: [],
      collection: "Sustainable Services",
      summary: "Reviews six tariff-setting methodologies used across our country programs, with decision criteria for when to use each and the political-economy assumptions each embeds.",
      views: 612, downloads: 177, pages: 20,
    },
    {
      id: 'd16',
      title: "Estudio de Caso: Operadores Rurales en Honduras",
      authors: ["Marcela Reyes"],
      type: "Case Study",
      thumb: "case",
      date: daysAgo(205),
      geography: ["Honduras"],
      topics: ["Service Delivery", "Community Finance"],
      tags: ["operadores", "Latin America", "case study"],
      language: "ES",
      partners: [],
      funders: [],
      collection: "Sustainable Services",
      summary: "Un estudio comparativo de seis operadores rurales hondureños y los factores institucionales que explican las diferencias de desempeño entre ellos.",
      views: 398, downloads: 112, pages: 24,
    },
    {
      id: 'd17',
      title: "Systems Change Framework — Illustrated",
      authors: ["Ellen Greggio"],
      type: "Presentation",
      thumb: "deck",
      date: daysAgo(220),
      geography: ["Global"],
      topics: ["Systems Change", "Strategy"],
      tags: ["framework", "systems", "strategy"],
      language: "EN",
      partners: [],
      funders: [],
      collection: "Learning & Innovation Agenda",
      summary: "Visual version of the Systems Change Framework, suitable for government and partner presentations. Includes facilitator notes and a 90-minute workshop plan.",
      views: 2811, downloads: 723, pages: 44,
    },
    {
      id: 'd18',
      title: "Annual Program Report 2025",
      authors: ["Program Team"],
      type: "Report",
      thumb: "tech",
      date: daysAgo(245),
      geography: ["Global"],
      topics: ["Strategy", "Service Delivery"],
      tags: ["annual report", "global"],
      language: "EN",
      partners: [],
      funders: [],
      collection: "Strategy",
      summary: "Program delivery outcomes, people reached, and financial sustainability indicators across all nine country programs for fiscal year 2025.",
      views: 5623, downloads: 2041, pages: 72,
    }
  ];

  // Derived facets
  const uniq = (arr) => Array.from(new Set(arr));
  const facets = {
    geography: uniq(docs.flatMap(d => d.geography)).sort(),
    topic: uniq(docs.flatMap(d => d.topics)).sort(),
    type: uniq(docs.map(d => d.type)).sort(),
    language: uniq(docs.map(d => d.language)).sort(),
    collection: uniq(docs.map(d => d.collection)).sort(),
    author: uniq(docs.flatMap(d => d.authors)).sort(),
  };

  const collections = [
    { id: "c1", title: "Scaling with Government", label: "Flagship", count: docs.filter(d => d.collection === 'Scaling with Government').length, color: 'c1' },
    { id: "c2", title: "Learning & Innovation Agenda", label: "Active", count: docs.filter(d => d.collection === 'Learning & Innovation Agenda').length, color: 'c2' },
    { id: "c3", title: "Sustainable Services", label: "Ongoing", count: docs.filter(d => d.collection === 'Sustainable Services').length, color: 'c3' },
    { id: "c4", title: "Climate & Resilience", label: "New", count: docs.filter(d => d.topics.includes('Climate')).length, color: 'c4' },
  ];

  // Suggested questions for ASK
  const suggestedQs = [
    "What have we learned about sustainable sanitation finance in Rwanda?",
    "How do our circuit-rider maintenance models perform across countries?",
    "Summarize our evidence on WASH in schools.",
    "Which countries have the strongest evidence on climate resilience?",
    "What are common drivers of tariff-setting success?"
  ];

  // Precomputed answers (used when AI is off, and as a fallback)
  const cannedAnswers = {
    "What have we learned about sustainable sanitation finance in Rwanda?": {
      answer: "Across three recent Rwanda-focused pieces, a consistent pattern emerges: community finance mechanisms (especially VSLAs) act as the critical bridge between household willingness-to-pay and infrastructure investment [1]. District-level WASH budget allocations have grown 34% in real terms since 2021/22, but inter-district variance remains high [2]. Sanitation MSMEs that survived the 2024 price shocks shared three traits — diversified product lines, proximity to cooperatives, and access to seasonal credit [3].",
      sources: ['d01', 'd02', 'd03']
    },
    "How do our circuit-rider maintenance models perform across countries?": {
      answer: "The Circuit-Rider Monitoring Framework reports coverage rates of 78–92% across Kenya, Malawi, and Honduras pilots, with median response times of 36 hours for reported breakdowns [1]. In Honduras specifically, six rural operators studied showed tight correlation between circuit-rider visits and tariff collection rates — suggesting the maintenance model also anchors financial behavior [2].",
      sources: ['d06', 'd16']
    },
    "Summarize our evidence on WASH in schools.": {
      answer: "Our strongest schools evidence sits in Honduras, where 312 schools have been certified under the Escuela Azul initiative, with hygiene behaviors sustained past project close [1]. A complementary Uganda piece documents how co-designing facilities with girls quietly but significantly improved uptake of menstrual health components [2].",
      sources: ['d05', 'd14']
    }
  };

  return { docs, facets, collections, suggestedQs, cannedAnswers };
})();
